# Generated by Django 4.0.6 on 2022-07-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_photoexposure_title_photonews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photonews', to='museum.news'),
        ),
    ]
