# Generated by Django 4.0.6 on 2022-07-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_photonews_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photonews',
            old_name='photo',
            new_name='image',
        ),
    ]
