# Generated by Django 4.0.6 on 2022-07-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_rename_photo_photonews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото экспозиции'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото новости'),
        ),
        migrations.AlterField(
            model_name='photoexposure',
            name='exposure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposurephoto', to='museum.exposure'),
        ),
    ]
