# Generated by Django 4.0.6 on 2022-07-30 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_exposure_photo_news_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExcursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фио')),
                ('email', models.EmailField(max_length=255, verbose_name='Емэйл')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('excursion', models.CharField(max_length=250, verbose_name='Экскурсия')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запись на экскурсию',
                'verbose_name_plural': 'Записи на экскурсии',
                'ordering': ['-excursion'],
            },
        ),
    ]
