# Generated by Django 4.0.6 on 2022-07-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_entryexcursions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexcursions',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='museum.excursions', verbose_name='Экскурсия'),
        ),
    ]
