# Generated by Django 4.0.6 on 2022-08-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_alter_entryexcursions_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoexposure',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Индекс'),
            preserve_default=False,
        ),
    ]
