# Generated by Django 4.0.6 on 2022-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_photoexposure_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='photonews',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Индекс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photoexposure',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото экспозиции'),
        ),
        migrations.AlterField(
            model_name='photonews',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото новости'),
        ),
    ]
